=== matthaiossaraj/mojikovancki4/Money/data.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="data">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="transactions">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="transaction" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="date"/>
                    <xs:element type="xs:string" name="tcategory"/>
                    <xs:element type="xs:float" name="amount"/>
                    <xs:element type="xs:string" name="taccount"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="type" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="accounts">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="account" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:float" name="balance"/>
                    <xs:element type="xs:short" name="limit"/>
                    <xs:element type="xs:string" name="type"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="categories">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:short" name="budget"/>
                    <xs:element type="xs:float" name="used"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== matthaiossaraj/mojikovancki4/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<data  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='data.xsd'>
    <transactions>
	<transaction type="income">
	    <date>23.10.2013</date>
	    <tcategory>Plaƒça</tcategory>
	    <amount>1000</amount>
	    <taccount>NLB</taccount>
	</transaction>
	<transaction type="income">
	    <date>25.10.2013</date>
	    <tcategory>Darilo</tcategory>
	    <amount>500</amount>
	    <taccount>NLB</taccount>
	</transaction>
	<transaction type="income">
	    <date>15.11.2013</date>
	    <tcategory>Darilo</tcategory>
	    <amount>2000</amount>
	    <taccount>NKBM</taccount>
	</transaction>
	<transaction type="outcome">
	    <date>1.11.2013</date>
	    <tcategory>Ostalo</tcategory>
	    <amount>12</amount>
	    <taccount>NLB</taccount>
	</transaction>
	<transaction type="outcome">
	    <date>3.11.2013</date>
	    <tcategory>Hrana</tcategory>
	    <amount>47.56</amount>
	    <taccount>NLB</taccount>
	</transaction>
	<transaction type="outcome">
	    <date>17.11.2013</date>
	    <tcategory>Zabava</tcategory>
	    <amount>35.34</amount>
	    <taccount>NKBM</taccount>
	</transaction>
	<transaction type="outcome">
	    <date>20.11.2013</date>
	    <tcategory>Prevoz</tcategory>
	    <amount>75.45</amount>
	    <taccount>NKBM</taccount>
	</transaction>
    </transactions>
    <accounts>
	<account>
	    <name>NLB</name>
	    <balance>657.78</balance>
	    <limit>1000</limit>
	    <type>TRR</type>
	</account>
	<account>
	    <name>NKBM</name>
	    <balance>1897.56</balance>
	    <limit>2000</limit>
	    <type>TRR</type>
	</account>
	<account>
	    <name>A banka</name>
	    <balance>-56.45</balance>
	    <limit>200</limit>
	    <type>TRR</type>
	</account>
    </accounts>
    <categories>
	<category>
	    <name>Hrana</name>
	    <budget>200</budget>
	    <used>76.56</used>
	</category>
	<category>
	    <name>Prevoz</name>
	    <budget>100</budget>
	    <used>46.56</used>
	</category>
	<category>
	    <name>Zabava</name>
	    <budget>100</budget>
	    <used>26.56</used>
	</category>
    </categories>
</data>
